'''
http://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

#store firstVal (1)
firstVal = 1
#store secondVal (2)
secondVal = 2

#store fibsum = secondVal
fibsum = 2

# while secondVal < 4 million
while secondVal < 4000000:
# # nextVal = firstVal + secondVal
   nextVal = firstVal + secondVal
# # if nextVal % 2 == 0
   if nextVal % 2 == 0:
# # # add nextVal to fibsum
      fibsum += nextVal
# # Set firstVal to secondVal
   firstVal = secondVal
# # set secondVal to nextVal
   secondVal = nextVal

# print fibsum

print fibsum

